version: "3.7" # optional since v1.27.0
services:
  postgres:
    hostname: postgres
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=aptms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass

networks:
  default:
    driver: bridge